# Generated by Django 5.0.2 on 2025-05-31 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(help_text='User who created this recipe', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Recipe author'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.ingredient', verbose_name='Ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ingredients used in this recipe', related_name='recipes', through='recipes.RecipeIngredient', to='recipes.ingredient', verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='userfavoriterecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='userfavoriterecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='usershoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_carts', to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='usershoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['recipe'], name='recipes_rec_recipe__6c6558_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['ingredient'], name='recipes_rec_ingredi_65e62b_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient_combination'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author'], name='recipes_rec_author__e2628b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['publication_date'], name='recipes_rec_publica_3fbb34_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['cooking_time'], name='recipes_rec_cooking_bf57fb_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_published'], name='recipes_rec_is_publ_8ba3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavoriterecipe',
            index=models.Index(fields=['user'], name='recipes_use_user_id_a7628e_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavoriterecipe',
            index=models.Index(fields=['recipe'], name='recipes_use_recipe__1ffabd_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavoriterecipe',
            index=models.Index(fields=['added_at'], name='recipes_use_added_a_f9e808_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfavoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_favorite_recipe'),
        ),
        migrations.AddIndex(
            model_name='usershoppingcart',
            index=models.Index(fields=['user'], name='recipes_use_user_id_bacb88_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppingcart',
            index=models.Index(fields=['recipe'], name='recipes_use_recipe__af640a_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppingcart',
            index=models.Index(fields=['added_at'], name='recipes_use_added_a_974647_idx'),
        ),
        migrations.AddConstraint(
            model_name='usershoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_shopping_cart_recipe'),
        ),
    ]
