# Generated by Django 5.0.2 on 2025-06-01 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Unit of measurement (max 200 characters, e.g., grams, cups, pieces)', max_length=200, verbose_name='Measurement unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Name of the ingredient (max 200 characters)', max_length=200, verbose_name='Ingredient name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Time required to prepare the recipe in minutes (1-32000)', validators=[django.core.validators.MinValueValidator(1, message='Cooking time must be at least 1 minute'), django.core.validators.MaxValueValidator(32000, message='Cooking time cannot exceed 32000 minutes')], verbose_name='Cooking time (minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Name of the recipe (max 200 characters)', max_length=200, verbose_name='Recipe name'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Amount of ingredient needed (1-32000)', validators=[django.core.validators.MinValueValidator(1, message='Amount must be at least 1'), django.core.validators.MaxValueValidator(32000, message='Amount cannot exceed 32000')], verbose_name='Amount'),
        ),
    ]
