# Generated by Django 5.0.2 on 2025-06-01 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_favorites_data(apps, schema_editor):
    """Migrate data from UserFavoriteRecipe to Favorite."""
    UserFavoriteRecipe = apps.get_model('recipes', 'UserFavoriteRecipe')
    Favorite = apps.get_model('recipes', 'Favorite')

    for old_favorite in UserFavoriteRecipe.objects.all():
        Favorite.objects.create(
            user=old_favorite.user,
            recipe=old_favorite.recipe
        )


def migrate_shopping_cart_data(apps, schema_editor):
    """Migrate data from UserShoppingCart to ShoppingCart."""
    UserShoppingCart = apps.get_model('recipes', 'UserShoppingCart')
    ShoppingCart = apps.get_model('recipes', 'ShoppingCart')

    for old_cart_item in UserShoppingCart.objects.all():
        ShoppingCart.objects.create(
            user=old_cart_item.user,
            recipe=old_cart_item.recipe
        )


def reverse_migrate_favorites_data(apps, schema_editor):
    """Reverse migration for favorites."""
    UserFavoriteRecipe = apps.get_model('recipes', 'UserFavoriteRecipe')
    Favorite = apps.get_model('recipes', 'Favorite')

    for favorite in Favorite.objects.all():
        UserFavoriteRecipe.objects.create(
            user=favorite.user,
            recipe=favorite.recipe
        )


def reverse_migrate_shopping_cart_data(apps, schema_editor):
    """Reverse migration for shopping cart."""
    UserShoppingCart = apps.get_model('recipes', 'UserShoppingCart')
    ShoppingCart = apps.get_model('recipes', 'ShoppingCart')

    for cart_item in ShoppingCart.objects.all():
        UserShoppingCart.objects.create(
            user=cart_item.user,
            recipe=cart_item.recipe
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        # Step 1: Create new models
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite recipe',
                'verbose_name_plural': 'Favorite recipes',
                'abstract': False,
                'default_related_name': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shopping cart item',
                'verbose_name_plural': 'Shopping cart items',
                'abstract': False,
                'default_related_name': 'shoppingcarts',
            },
        ),

        # Step 2: Migrate data
        migrations.RunPython(
            migrate_favorites_data,
            reverse_migrate_favorites_data
        ),
        migrations.RunPython(
            migrate_shopping_cart_data,
            reverse_migrate_shopping_cart_data
        ),

        # Step 3: Remove index first, then field
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_is_publ_8ba3bf_idx',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_published',
        ),
        migrations.DeleteModel(
            name='UserFavoriteRecipe',
        ),
        migrations.DeleteModel(
            name='UserShoppingCart',
        ),

        # Step 4: Add new fields to Recipe
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', through='recipes.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Users who favorited this recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_shopping_carts',
            field=models.ManyToManyField(blank=True, related_name='shopping_cart_recipes', through='recipes.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Users who added this recipe to shopping cart'),
        ),

        # Step 5: Add constraints and indexes
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes_favorite_unique_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes_shoppingcart_unique_user_recipe'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'recipe'], name='recipes_fav_user_recipe_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user', 'recipe'], name='recipes_shop_user_recipe_idx'),
        ),
    ]
