# Generated by Django 5.0.2 on 2025-06-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250601_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Favorite recipe', 'verbose_name_plural': 'Favorite recipes'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Shopping cart item', 'verbose_name_plural': 'Shopping cart items'},
        ),
        migrations.RenameIndex(
            model_name='favorite',
            new_name='recipes_fav_user_id_b3978f_idx',
            old_name='recipes_fav_user_recipe_idx',
        ),
        migrations.RenameIndex(
            model_name='shoppingcart',
            new_name='recipes_sho_user_id_212d34_idx',
            old_name='recipes_shop_user_recipe_idx',
        ),
    ]
